<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

use App\Models\LeftMenu;
use Illuminate\Support\Facades\Hash;

class LeftMenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $insertdata = [
            [
                "id" => "1",
                "name" => "Dashboard",
                "namekey" => "dashboard",
                "link" => "home",
                "icon" => "fa fa-dashboard",
                "parent_id" => "0",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "0",
                "created" => "2018-09-18 15:13:43",
                "updated" => "2020-11-23 15:13:14",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "2",
                "name" => "Employee Management",
                "namekey" => "employee_management",
                "link" => null,
                "icon" => "fa fa-desktop",
                "parent_id" => "0",
                "is_parent" => "1",
                "is_module" => "1",
                "modkey" => "",
                "sort_order" => "0",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2018-09-18 18:02:22",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "3",
                "name" => "Project Management",
                "namekey" => "project_management",
                "link" => null,
                "icon" => "fa fa-th",
                "parent_id" => "0",
                "is_parent" => "1",
                "is_module" => "1",
                "modkey" => "",
                "sort_order" => "0",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2018-09-18 18:05:09",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "4",
                "name" => "Timesheet",
                "namekey" => "timesheet",
                "link" => null,
                "icon" => "fa fa-book",
                "parent_id" => "0",
                "is_parent" => "1",
                "is_module" => "1",
                "modkey" => "",
                "sort_order" => "0",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2018-10-23 09:58:46",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "5",
                "name" => "Attendance",
                "namekey" => "attendance",
                "link" => null,
                "icon" => "fa fa-calendar",
                "parent_id" => "0",
                "is_parent" => "1",
                "is_module" => "1",
                "modkey" => "",
                "sort_order" => "0",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2018-09-18 18:02:54",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "6",
                "name" => "New Employee",
                "namekey" => "new_employee",
                "link" => "new_employee",
                "icon" => "fa fa-dashboard",
                "parent_id" => "2",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "1",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2018-11-13 12:27:50",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "7",
                "name" => "Project",
                "namekey" => "project",
                "link" => "project",
                "icon" => "fa fa-dashboard",
                "parent_id" => "3",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "0",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2018-12-12 19:17:13",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "8",
                "name" => "Task",
                "namekey" => "task",
                "link" => "Project/task",
                "icon" => "fa fa-dashboard",
                "parent_id" => "3",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "0",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2018-09-24 13:00:19",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "9",
                "name" => "My Task",
                "namekey" => "my_task",
                "link" => "Project/mytask",
                "icon" => "fa fa-dashboard",
                "parent_id" => "3",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "0",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2018-09-24 13:00:23",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "10",
                "name" => "Attendance Details",
                "namekey" => "attendance_details",
                "link" => "attendance_details",
                "icon" => "fa fa-dashboard",
                "parent_id" => "5",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "2",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-05-28 10:24:44",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "11",
                "name" => "Employee List",
                "namekey" => "employee_list",
                "link" => "employee_list",
                "icon" => "fa fa-dashboard",
                "parent_id" => "2",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "0",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2018-10-03 11:30:53",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "12",
                "name" => "Server Details",
                "namekey" => "Server Details",
                "link" => "",
                "icon" => "fa fa-book",
                "parent_id" => "0",
                "is_parent" => "1",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "0",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-09-26 20:45:30",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "13",
                "name" => "Embassy List",
                "namekey" => "Embassy List",
                "link" => "embassy_list",
                "icon" => "fa fa-book",
                "parent_id" => "12",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "0",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-09-26 19:34:39",
                "status" => "0",
                "trash" => "YES"
            ],
            [
                "id" => "14",
                "name" => "Product Management",
                "namekey" => "Product Management",
                "link" => null,
                "icon" => "fa fa-desktop",
                "parent_id" => "0",
                "is_parent" => "1",
                "is_module" => "1",
                "modkey" => "",
                "sort_order" => "0",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2018-09-18 18:02:22",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "15",
                "name" => "GRN",
                "namekey" => "GRN",
                "link" => "new_grn",
                "icon" => "fa fa-book",
                "parent_id" => "14",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "0",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2018-11-08 18:10:10",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "16",
                "name" => "Attendance Reconciliation",
                "namekey" => "Attendance Reconciliation",
                "link" => "attendance_reconciliation",
                "icon" => "fa fa-dashboard",
                "parent_id" => "5",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "8",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-05-28 10:17:07",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "17",
                "name" => "System Management",
                "namekey" => "System Management",
                "link" => null,
                "icon" => "fa fa-desktop",
                "parent_id" => "0",
                "is_parent" => "1",
                "is_module" => "1",
                "modkey" => "",
                "sort_order" => "1",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-07-05 14:37:44",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "18",
                "name" => "Request",
                "namekey" => "Request",
                "link" => "network_problem_lists",
                "icon" => "fa fa-dashboard",
                "parent_id" => "17",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "0",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2018-10-23 14:40:58",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "19",
                "name" => "Request",
                "namekey" => "Request",
                "link" => "view_problem_lists",
                "icon" => "fa fa-dashboard",
                "parent_id" => "17",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "0",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2018-10-24 16:23:40",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "20",
                "name" => "Holidays",
                "namekey" => "Holidays",
                "link" => "holidays",
                "icon" => "fa fa-dashboard",
                "parent_id" => "5",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "9",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-05-28 10:17:10",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "21",
                "name" => "Vendor",
                "namekey" => "Vendor",
                "link" => "vendor_list",
                "icon" => "fa fa-book",
                "parent_id" => "14",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "0",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2018-10-04 12:37:44",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "22",
                "name" => "Timesheets",
                "namekey" => "Timesheets",
                "link" => "date_view_timesheet",
                "icon" => "fa fa-book",
                "parent_id" => "4",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "1",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-06-04 18:31:39",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "23",
                "name" => "Calender",
                "namekey" => "Calender",
                "link" => "calender_view",
                "icon" => "fa fa-dashboard",
                "parent_id" => "5",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "0",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-05-28 10:24:39",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "24",
                "name" => "Inventory",
                "namekey" => "Inventory",
                "link" => "my_inventory",
                "icon" => "fa fa-setting",
                "parent_id" => "14",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "0",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2018-11-29 12:16:02",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "25",
                "name" => "Live Track",
                "namekey" => "live_track",
                "link" => "live_track",
                "icon" => "fa fa-dashboard",
                "parent_id" => "5",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "1",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-05-28 10:24:51",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "26",
                "name" => "Permission",
                "namekey" => "permission",
                "link" => "permission",
                "icon" => "fa fa-dashboard",
                "parent_id" => "5",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "3",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2018-12-12 11:00:51",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "27",
                "name" => "On-Duty",
                "namekey" => "on_duty",
                "link" => "on_duty",
                "icon" => "fa fa-dashboard",
                "parent_id" => "5",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "4",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2018-12-12 11:00:48",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "28",
                "name" => "Work at Home",
                "namekey" => "work_at_home",
                "link" => "work_at_home",
                "icon" => "fa fa-dashboard",
                "parent_id" => "5",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "5",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2018-12-12 11:00:44",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "29",
                "name" => "Leave",
                "namekey" => "leave",
                "link" => "leave",
                "icon" => "fa fa-dashboard",
                "parent_id" => "5",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "6",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2018-12-12 15:02:04",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "30",
                "name" => "My Attendance",
                "namekey" => "my_attendance",
                "link" => null,
                "icon" => "fa fa-calendar",
                "parent_id" => "0",
                "is_parent" => "1",
                "is_module" => "1",
                "modkey" => "",
                "sort_order" => "0",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2018-09-18 18:02:54",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "31",
                "name" => "My Attendance Details",
                "namekey" => "my_attendance_details",
                "link" => "my_attendance",
                "icon" => "fa fa-dashboard",
                "parent_id" => "30",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "2",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-05-28 10:24:48",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "32",
                "name" => "My Live Track",
                "namekey" => "my_live_track",
                "link" => "my_live_track",
                "icon" => "fa fa-dashboard",
                "parent_id" => "30",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "1",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-05-28 10:24:50",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "33",
                "name" => "My Permission",
                "namekey" => "my_permission",
                "link" => "my_permission",
                "icon" => "fa fa-dashboard",
                "parent_id" => "30",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "3",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2018-12-14 10:28:21",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "34",
                "name" => "My On-Duty",
                "namekey" => "my_on_duty",
                "link" => "my_on_duty",
                "icon" => "fa fa-dashboard",
                "parent_id" => "30",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "4",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2018-12-13 20:33:48",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "35",
                "name" => "My Work at Home",
                "namekey" => "my_work_at_home",
                "link" => "my_work_at_home",
                "icon" => "fa fa-dashboard",
                "parent_id" => "30",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "5",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2018-12-13 20:33:50",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "36",
                "name" => "My Leave",
                "namekey" => "my_leave",
                "link" => "my_leave",
                "icon" => "fa fa-dashboard",
                "parent_id" => "30",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "6",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2018-12-13 20:33:52",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "37",
                "name" => "Holidays",
                "namekey" => "Holidays",
                "link" => "view_holidays",
                "icon" => "fa fa-dashboard",
                "parent_id" => "30",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "9",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-05-28 10:18:56",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "38",
                "name" => "Bug Sheet",
                "namekey" => "bug_sheet",
                "link" => "bug_sheet",
                "icon" => "fa fa-dashboard",
                "parent_id" => "3",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "0",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2018-09-24 13:00:23",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "39",
                "name" => "Ardhas Server",
                "namekey" => "Ardhas Server",
                "link" => "ardhas_server_list",
                "icon" => "fa fa-book",
                "parent_id" => "12",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "0",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-09-26 19:34:41",
                "status" => "0",
                "trash" => "YES"
            ],
            [
                "id" => "40",
                "name" => "Add Timesheet",
                "namekey" => "add_timesheet_form",
                "link" => "add_timesheet_form",
                "icon" => "fa fa-book",
                "parent_id" => "4",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "4",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-06-04 18:31:49",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "41",
                "name" => "Report",
                "namekey" => "Report",
                "link" => null,
                "icon" => "fa fa-desktop",
                "parent_id" => "0",
                "is_parent" => "1",
                "is_module" => "1",
                "modkey" => "",
                "sort_order" => "1",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-07-05 14:37:39",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "42",
                "name" => "Project Report",
                "namekey" => "Project Report",
                "link" => "project_report",
                "icon" => "fa fa-book",
                "parent_id" => "41",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "1",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2018-11-13 14:04:50",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "43",
                "name" => "Exist Employee",
                "namekey" => "exist_employee",
                "link" => "exist_employee",
                "icon" => "fa fa-dashboard",
                "parent_id" => "2",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "1",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2018-11-13 12:27:50",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "44",
                "name" => "Team Time Sheet",
                "namekey" => "Team Time Sheet",
                "link" => "team_time_sheets",
                "icon" => "fa fa-book",
                "parent_id" => "4",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "3",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-06-04 18:31:53",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "45",
                "name" => "
       Current Project Report",
                "namekey" => "Current Project Report",
                "link" => "current_project_report",
                "icon" => "fa fa-book",
                "parent_id" => "41",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "1",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2018-11-13 14:04:50",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "46",
                "name" => "Timesheet Calender",
                "namekey" => "Calender",
                "link" => "time_sheet_calender",
                "icon" => "fa fa-book",
                "parent_id" => "4",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "2",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-06-04 18:31:55",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "47",
                "name" => "Team Calendar",
                "namekey" => "Team Calendar",
                "link" => "team_time_sheet_calender",
                "icon" => "fa fa-book",
                "parent_id" => "4",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "0",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-05-28 10:31:53",
                "status" => "1",
                "trash" => "YES"
            ],
            [
                "id" => "48",
                "name" => "My Work Request",
                "namekey" => "work request",
                "link" => "my_work_request",
                "icon" => "fa fa-dashboard",
                "parent_id" => "30",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "7",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-03-21 17:16:49",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "49",
                "name" => "Work Request",
                "namekey" => "work_request",
                "link" => "work_request",
                "icon" => "fa fa-dashboard",
                "parent_id" => "5",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "7",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-05-28 10:17:04",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "50",
                "name" => "My Attendance Reconciliation",
                "namekey" => "my_attendance_reconciliation",
                "link" => "my_attendance_reconciliation",
                "icon" => "fa fa-dashboard",
                "parent_id" => "30",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "8",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-05-28 10:18:54",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "51",
                "name" => "Payroll",
                "namekey" => "Payroll",
                "link" => null,
                "icon" => "fa fa-money",
                "parent_id" => "0",
                "is_parent" => "1",
                "is_module" => "1",
                "modkey" => "",
                "sort_order" => "1",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-07-05 14:37:35",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "52",
                "name" => "Payroll Calculation",
                "namekey" => "payroll_calculation",
                "link" => "payroll_calculation",
                "icon" => "fa fa-dashboard",
                "parent_id" => "51",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "2",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-04-25 11:19:23",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "53",
                "name" => "Payslip",
                "namekey" => "payslip",
                "link" => "payslip",
                "icon" => "fa fa-dashboard",
                "parent_id" => "51",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "2",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-04-25 11:19:23",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "54",
                "name" => "Employee Payslip",
                "namekey" => "Employee Payslip",
                "link" => "employee_payslip",
                "icon" => "fa fa-dashboard",
                "parent_id" => "51",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "2",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-04-25 11:19:23",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "55",
                "name" => "Mail Management",
                "namekey" => "Mail Management",
                "link" => null,
                "icon" => "fa fa-envelope",
                "parent_id" => "0",
                "is_parent" => "1",
                "is_module" => "1",
                "modkey" => "",
                "sort_order" => "1",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-07-05 14:37:28",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "56",
                "name" => "Compose mail ",
                "namekey" => "Sent Mail ",
                "link" => "sent_mail",
                "icon" => "fa fa-dashboard",
                "parent_id" => "55",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "2",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-05-27 14:54:45",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "57",
                "name" => "CRM",
                "namekey" => "CRM",
                "link" => null,
                "icon" => "fa fa-users",
                "parent_id" => "0",
                "is_parent" => "1",
                "is_module" => "1",
                "modkey" => "",
                "sort_order" => "0",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2018-09-18 18:02:54",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "58",
                "name" => "Lead Post",
                "namekey" => "Lead",
                "link" => "lead",
                "icon" => "fa fa-dashboard",
                "parent_id" => "57",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "2",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-05-27 14:54:45",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "59",
                "name" => "Master",
                "namekey" => "Master",
                "link" => null,
                "icon" => "fa fa-envelope",
                "parent_id" => "0",
                "is_parent" => "1",
                "is_module" => "1",
                "modkey" => "",
                "sort_order" => "0",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-05-27 17:47:39",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "60",
                "name" => "Project Framework",
                "namekey" => "Project Framework",
                "link" => "project_framework",
                "icon" => "fa fa-dashboard",
                "parent_id" => "59",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "1",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-05-28 10:49:39",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "61",
                "name" => "Project Category",
                "namekey" => "Project Category",
                "link" => "project_category",
                "icon" => "fa fa-dashboard",
                "parent_id" => "59",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "2",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-05-28 10:49:42",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "62",
                "name" => "Blood Group",
                "namekey" => "Blood Group",
                "link" => "blood_group",
                "icon" => "fa fa-dashboard",
                "parent_id" => "59",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "3",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-05-28 10:49:42",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "63",
                "name" => "Department",
                "namekey" => "Department",
                "link" => "department",
                "icon" => "fa fa-dashboard",
                "parent_id" => "59",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "4",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-05-28 10:49:42",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "64",
                "name" => "Designation",
                "namekey" => "Designation",
                "link" => "designation",
                "icon" => "fa fa-dashboard",
                "parent_id" => "59",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "5",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-05-28 10:49:42",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "65",
                "name" => "Role",
                "namekey" => "Role",
                "link" => "role",
                "icon" => "fa fa-dashboard",
                "parent_id" => "59",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "6",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-05-28 10:49:42",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "66",
                "name" => "Employee Type",
                "namekey" => "Employee Type",
                "link" => "employee_type",
                "icon" => "fa fa-dashboard",
                "parent_id" => "59",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "7",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-05-28 10:49:42",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "67",
                "name" => "Embassy Shift",
                "namekey" => "Embassy Shift",
                "link" => null,
                "icon" => "fa fa-money",
                "parent_id" => "0",
                "is_parent" => "1",
                "is_module" => "1",
                "modkey" => "",
                "sort_order" => "0",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2018-09-18 18:02:54",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "68",
                "name" => "Add Shift",
                "namekey" => "Add Shift",
                "link" => "add_shift",
                "icon" => "fa fa-dashboard",
                "parent_id" => "67",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "2",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-05-30 17:27:32",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "69",
                "name" => "Shift List",
                "namekey" => "Shift List",
                "link" => "shift_list",
                "icon" => "fa fa-dashboard",
                "parent_id" => "67",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "1",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-06-25 11:04:28",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "70",
                "name" => "Role Management",
                "namekey" => "Role Management",
                "link" => null,
                "icon" => "fa fa-dashboard",
                "parent_id" => "0",
                "is_parent" => "1",
                "is_module" => "1",
                "modkey" => "",
                "sort_order" => "0",
                "created" => "2018-09-18 15:13:43",
                "updated" => "2019-06-07 13:43:49",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "71",
                "name" => "Role",
                "namekey" => "Role",
                "link" => "view_permissions",
                "icon" => "fa fa-book",
                "parent_id" => "70",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "0",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-06-07 13:43:57",
                "status" => "1",
                "trash" => "YES"
            ],
            [
                "id" => "72",
                "name" => "WebMail",
                "namekey" => "WebMail",
                "link" => "webmail",
                "icon" => "fa fa-dashboard",
                "parent_id" => "55",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "2",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-05-27 14:54:45",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "73",
                "name" => "IP Management",
                "namekey" => "IP Management",
                "link" => null,
                "icon" => "fa fa-dashboard",
                "parent_id" => "0",
                "is_parent" => "1",
                "is_module" => "1",
                "modkey" => "",
                "sort_order" => "0",
                "created" => "2018-09-18 15:13:43",
                "updated" => "2019-06-07 13:43:49",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "74",
                "name" => "Add User",
                "namekey" => "Add User",
                "link" => "add_ip",
                "icon" => "fa fa-book",
                "parent_id" => "73",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "0",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-06-07 13:43:57",
                "status" => "1",
                "trash" => "YES"
            ],
            [
                "id" => "75",
                "name" => "IP Users",
                "namekey" => "ip_users",
                "link" => "ip_users",
                "icon" => "fa fa-book",
                "parent_id" => "73",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "0",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-06-07 13:43:57",
                "status" => "1",
                "trash" => "YES"
            ],
            [
                "id" => "76",
                "name" => "CRM",
                "namekey" => "CRM",
                "link" => null,
                "icon" => "fa fa-dashboard",
                "parent_id" => "0",
                "is_parent" => "1",
                "is_module" => "1",
                "modkey" => "",
                "sort_order" => "0",
                "created" => "2018-09-18 15:13:43",
                "updated" => "2019-06-07 13:43:49",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "77",
                "name" => "Add Leads",
                "namekey" => "Add Leads",
                "link" => "add_lead_from",
                "icon" => "fa fa-book",
                "parent_id" => "76",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "3",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-06-28 12:19:27",
                "status" => "1",
                "trash" => "YES"
            ],
            [
                "id" => "78",
                "name" => "Lead List",
                "namekey" => "leads",
                "link" => "leads",
                "icon" => "fa fa-book",
                "parent_id" => "76",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "1",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-06-28 12:19:21",
                "status" => "1",
                "trash" => "YES"
            ],
            [
                "id" => "79",
                "name" => "My Lead List",
                "namekey" => "My Lead List",
                "link" => "my_lead",
                "icon" => "fa fa-book",
                "parent_id" => "76",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "2",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-06-28 12:19:25",
                "status" => "1",
                "trash" => "YES"
            ],
            [
                "id" => "80",
                "name" => "Country Master",
                "namekey" => "Country Master",
                "link" => "continents",
                "icon" => "fa fa-dashboard",
                "parent_id" => "59",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "4",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-06-11 12:34:33",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "81",
                "name" => "Company Master",
                "namekey" => "Company Master",
                "link" => "company_master",
                "icon" => "fa fa-dashboard",
                "parent_id" => "59",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "4",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-06-28 17:38:41",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "82",
                "name" => "My Manual Punch",
                "namekey" => "my_manual_punch",
                "link" => "my_manual_punch",
                "icon" => "fa fa-dashboard",
                "parent_id" => "30",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "4",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-06-12 13:19:15",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "83",
                "name" => "Manual Punch",
                "namekey" => "manual_punch",
                "link" => "manual_punch",
                "icon" => "fa fa-dashboard",
                "parent_id" => "5",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "4",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-06-12 13:19:29",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "84",
                "name" => "Time Line crossed Project",
                "namekey" => "Time Line crossed Project",
                "link" => "project_timeline",
                "icon" => "fa fa-book",
                "parent_id" => "41",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "1",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2018-11-13 14:04:50",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "85",
                "name" => "Add New Leads",
                "namekey" => "Add New Leads",
                "link" => "crn_new_lead",
                "icon" => "fa fa-dashboard",
                "parent_id" => "76",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "4",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-08-30 15:01:51",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "86",
                "name" => "All Leads",
                "namekey" => "Leads",
                "link" => "crn_lists",
                "icon" => "fa fa-dashboard",
                "parent_id" => "76",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "4",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-07-01 19:16:47",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "87",
                "name" => "Unassigned Leads",
                "namekey" => "Unassigned Leads",
                "link" => "unassigned_crn_lists",
                "icon" => "fa fa-dashboard",
                "parent_id" => "76",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "4",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-07-01 19:16:47",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "88",
                "name" => "My Leads",
                "namekey" => "My Leads",
                "link" => "my_crn_lists",
                "icon" => "fa fa-dashboard",
                "parent_id" => "76",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "4",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-07-01 19:16:47",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "89",
                "name" => "My Remainder",
                "namekey" => "My Remainder",
                "link" => "my_remainder",
                "icon" => "fa fa-dashboard",
                "parent_id" => "76",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "4",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-07-03 11:33:54",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "90",
                "name" => "Report",
                "namekey" => "Report",
                "link" => "crn_report",
                "icon" => "fa fa-dashboard",
                "parent_id" => "76",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "4",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-07-03 11:33:54",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "91",
                "name" => "LOG Management",
                "namekey" => "Log Management",
                "link" => null,
                "icon" => "fa fa-dashboard",
                "parent_id" => "0",
                "is_parent" => "1",
                "is_module" => "1",
                "modkey" => "",
                "sort_order" => "0",
                "created" => "2018-09-18 15:13:43",
                "updated" => "2019-06-07 13:43:49",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "92",
                "name" => "Logs",
                "namekey" => "Logs",
                "link" => "log_report",
                "icon" => "fa fa-dashboard",
                "parent_id" => "91",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "4",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-07-08 12:04:19",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "93",
                "name" => "List of Embassy",
                "namekey" => "List of Embassy",
                "link" => "list_of_embassy_list",
                "icon" => "fa fa-book",
                "parent_id" => "12",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "0",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-09-26 19:34:33",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "94",
                "name" => "Domain List",
                "namekey" => "Domain List",
                "link" => "domain_list",
                "icon" => "fa fa-book",
                "parent_id" => "12",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "1",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-09-26 19:36:19",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "95",
                "name" => "Server List",
                "namekey" => "Server List",
                "link" => "server_list",
                "icon" => "fa fa-book",
                "parent_id" => "12",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "2",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-09-26 19:36:19",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "96",
                "name" => "Mail Server List",
                "namekey" => "Mail Server List",
                "link" => "mail_server_list",
                "icon" => "fa fa-book",
                "parent_id" => "12",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "3",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-09-26 19:36:19",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "97",
                "name" => "SSL List",
                "namekey" => "SSL List",
                "link" => "ssl_list",
                "icon" => "fa fa-book",
                "parent_id" => "12",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "4",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-09-26 19:36:19",
                "status" => "1",
                "trash" => "NO"
            ],
            [
                "id" => "98",
                "name" => "Ardhas Website list",
                "namekey" => "Ardhas Website list",
                "link" => "ardhas_website_list",
                "icon" => "fa fa-book",
                "parent_id" => "12",
                "is_parent" => "0",
                "is_module" => "0",
                "modkey" => "",
                "sort_order" => "5",
                "created" => "2018-09-18 15:15:38",
                "updated" => "2019-09-26 19:36:19",
                "status" => "1",
                "trash" => "NO"
            ]
        ];

        LeftMenu::truncate();
        LeftMenu::insert($insertdata);
    }
}
