<?php


defined('INSPECTION_TYPE_BOAT') or define('INSPECTION_TYPE_BOAT', 1);
defined('INSPECTION_TYPE_BUILDING_OFFICE') or define('INSPECTION_TYPE_BUILDING_OFFICE', 2);
defined('INSPECTION_TYPE_BUILDING_OFFICE_CARETAKER') or define('INSPECTION_TYPE_BUILDING_OFFICE_CARETAKER', 3);
defined('INSPECTION_TYPE_CONTAINER_FORKLIFT') or define('INSPECTION_TYPE_CONTAINER_FORKLIFT', 4);
defined('INSPECTION_TYPE_FIRST_AID') or define('INSPECTION_TYPE_FIRST_AID', 5);
defined('INSPECTION_TYPE_FORKLIFT') or define('INSPECTION_TYPE_FORKLIFT', 6);
defined('INSPECTION_TYPE_REACH_STACKER') or define('INSPECTION_TYPE_REACH_STACKER', 7);
defined('INSPECTION_TYPE_TERMINAL') or define('INSPECTION_TYPE_TERMINAL', 8);
defined('INSPECTION_TYPE_WORKSHOP') or define('INSPECTION_TYPE_WORKSHOP', 9);
defined('INSPECTION_JETTY_AUDIT') or define('INSPECTION_JETTY_AUDIT', 10);

defined('INSPECTION_STATUS_ASSIGNED') or define('INSPECTION_STATUS_ASSIGNED', 1);
defined('INSPECTION_STATUS_INSPECTION_COMPLETED') or define('INSPECTION_STATUS_INSPECTION_COMPLETED', 2);
defined('INSPECTION_STATUS_HOD_APPROVED') or define('INSPECTION_STATUS_HOD_APPROVED', 3);
defined('INSPECTION_STATUS_HOD_REJECTED') or define('INSPECTION_STATUS_HOD_REJECTED', 4);
defined('INSPECTION_STATUS_CLOSED') or define('INSPECTION_STATUS_CLOSED', 5);
