<?php

defined('PTW_SUB_WORK_STATUS_NOT_REQUIRE') or define('PTW_SUB_WORK_STATUS_NOT_REQUIRE', 0);
defined('PTW_SUB_WORK_STATUS_PENDING') or define('PTW_SUB_WORK_STATUS_PENDING', 1);
defined('PTW_SUB_WORK_STATUS_COMPLETED') or define('PTW_SUB_WORK_STATUS_COMPLETED', 2);


defined('PTW_PERMIT_GENERAL') or define('PTW_PERMIT_GENERAL', 0);
defined('PTW_SUB_PERMIT_GAS') or define('PTW_SUB_PERMIT_GAS', 1);
defined('PTW_SUB_PERMIT_ISOLATION') or define('PTW_SUB_PERMIT_ISOLATION', 2);
defined('PTW_SUB_PERMIT_SURFACE') or define('PTW_SUB_PERMIT_SURFACE', 3);
defined('PTW_SUB_PERMIT_HOTWORK') or define('PTW_SUB_PERMIT_HOTWORK', 4);
defined('PTW_SUB_PERMIT_WORKTRAFFIC') or define('PTW_SUB_PERMIT_WORKTRAFFIC', 5);
defined('PTW_SUB_PERMIT_LIFTING') or define('PTW_SUB_PERMIT_LIFTING', 6);
defined('PTW_SUB_PERMIT_DIVING') or define('PTW_SUB_PERMIT_DIVING', 7);

/**
 * PTW Master Category
 */

defined('PTW_CAT_GENERAL_HAZARD') or define('PTW_CAT_GENERAL_HAZARD', 1);
defined('PTW_CAT_GENERAL_SUPPORT_DOCUMENT') or define('PTW_CAT_GENERAL_SUPPORT_DOCUMENT', 2);
defined('PTW_CAT_GENERAL_EQUIPEMNT') or define('PTW_CAT_GENERAL_EQUIPEMNT', 3);
defined('PTW_CAT_GENERAL_SITE_PREPARATION') or define('PTW_CAT_GENERAL_SITE_PREPARATION', 4);
defined('PTW_CAT_GENERAL_PERMIT_ISSUE') or define('PTW_CAT_GENERAL_PERMIT_ISSUE', 5);
defined('PTW_CAT_GENERAL_REVALIDATION') or define('PTW_CAT_GENERAL_REVALIDATION', 6);
defined('PTW_CAT_GENERAL_HANDBACK') or define('PTW_CAT_GENERAL_HANDBACK', 7);
defined('PTW_CAT_ISOLATION_PPE') or define('PTW_CAT_ISOLATION_PPE', 8);
defined('PTW_CAT_SURFACE_PPE') or define('PTW_CAT_SURFACE_PPE', 9);
defined('PTW_CAT_SURFACE_EQUIPMENT') or define('PTW_CAT_SURFACE_EQUIPMENT', 10);
defined('PTW_CAT_SURFACE_ADDITIONAL_REQUIREMENTS') or define('PTW_CAT_SURFACE_ADDITIONAL_REQUIREMENTS', 11);
defined('PTW_CAT_HOTWORK_WORK_OPERATION') or define('PTW_CAT_HOTWORK_WORK_OPERATION', 12);
defined('PTW_CAT_HOTWORK_PRECAUTIONS') or define('PTW_CAT_HOTWORK_PRECAUTIONS', 13);
defined('PTW_CAT_TRAFFIC_DETAILS_LIGHT') or define('PTW_CAT_TRAFFIC_DETAILS_LIGHT', 14);
defined('PTW_CAT_TRAFFIC_DETAILS_OTHERS') or define('PTW_CAT_TRAFFIC_DETAILS_OTHERS', 15);
defined('PTW_CAT_LIFTING_EQUIPMENT') or define('PTW_CAT_LIFTING_EQUIPMENT', 16);
defined('PTW_CAT_LIFTING_RIGGING') or define('PTW_CAT_LIFTING_RIGGING', 17);
defined('PTW_CAT_DIVING_EQUIPMENT') or define('PTW_CAT_DIVING_EQUIPMENT', 18);
defined('PTW_CAT_DIVING_SITE_PREPARATION') or define('PTW_CAT_DIVING_SITE_PREPARATION', 19);

defined('VALIDITY_GENERAL') or define('VALIDITY_GENERAL', 7);
defined('VALIDITY_GENERAL_MONTH') or define('VALIDITY_GENERAL_MONTH', 30);
defined('VALIDITY_GAS') or define('VALIDITY_GAS', 1);
defined('VALIDITY_ISOLATION') or define('VALIDITY_ISOLATION', 7);
defined('VALIDITY_SURFACE') or define('VALIDITY_SURFACE', 7);
defined('VALIDITY_HOTWORK') or define('VALIDITY_HOTWORK', 1);
defined('VALIDITY_TRAFFIC') or define('VALIDITY_TRAFFIC', 7);
defined('VALIDITY_LIFTING') or define('VALIDITY_LIFTING', 7);
defined('VALIDITY_DIVING') or define('VALIDITY_DIVING', 7);

defined('SUBPERMIT_STATUS_NOT_APPLIED') or define('SUBPERMIT_STATUS_NOT_APPLIED', 0);
defined('SUBPERMIT_STATUS_PENDING') or define('SUBPERMIT_STATUS_PENDING', 1);
defined('SUBPERMIT_STATUS_APPROVED') or define('SUBPERMIT_STATUS_APPROVED', 2);
defined('SUBPERMIT_STATUS_REJECTED') or define('SUBPERMIT_STATUS_REJECTED', 3);
defined('SUBPERMIT_STATUS_EXPIRED') or define('SUBPERMIT_STATUS_EXPIRED', 4);
defined('SUBPERMIT_STATUS_CLOSED') or define('SUBPERMIT_STATUS_CLOSED', 5);

defined('SUBPERMIT_NAME_PENDING') or define('SUBPERMIT_NAME_PENDING', 'Pending');
defined('SUBPERMIT_NAME_APPROVED') or define('SUBPERMIT_NAME_APPROVED', 'Approved');
defined('SUBPERMIT_NAME_REJECTED') or define('SUBPERMIT_NAME_REJECTED', 'Rejected');
defined('SUBPERMIT_NAME_EXPIRED') or define('SUBPERMIT_NAME_EXPIRED', 'Expired');
defined('SUBPERMIT_NAME_CLOSED') or define('SUBPERMIT_NAME_CLOSED', 'Closed');

defined('PERMIT_STATUS_SP_PENDING') or define('PERMIT_STATUS_SP_PENDING', 1);
defined('PERMIT_STATUS_AO_PENDING') or define('PERMIT_STATUS_AO_PENDING', 2);
defined('PERMIT_STATUS_AO_REJECTED') or define('PERMIT_STATUS_AO_REJECTED', 3);
defined('PERMIT_STATUS_GHSE_PENDING') or define('PERMIT_STATUS_GHSE_PENDING', 4);
defined('PERMIT_STATUS_GHSE_REJECTED') or define('PERMIT_STATUS_GHSE_REJECTED', 5);
defined('PERMIT_STATUS_SA_PENDING') or define('PERMIT_STATUS_SA_PENDING', 6);
defined('PERMIT_STATUS_SA_REJECTED') or define('PERMIT_STATUS_SA_REJECTED', 7);
defined('PERMIT_STATUS_PTW_APPROVED') or define('PERMIT_STATUS_PTW_APPROVED', 8);
defined('PERMIT_STATUS_PTW_EXPIRED') or define('PERMIT_STATUS_PTW_EXPIRED', 9);
defined('PERMIT_STATUS_PTW_CLOSED') or define('PERMIT_STATUS_PTW_CLOSED', 10);
defined('PERMIT_STATUS_PTW_HOLD') or define('PERMIT_STATUS_PTW_HOLD', 11);
defined('PERMIT_STATUS_ADDITIONAL_SP_PENDING') or define('PERMIT_STATUS_ADDITIONAL_SP_PENDING', 12);
defined('PERMIT_STATUS_DRAFT') or define('PERMIT_STATUS_DRAFT', 13);

defined('PTW_RISK_MATRIX_LOW') or define('PTW_RISK_MATRIX_LOW', '#0ca747');
defined('PTW_RISK_MATRIX_MEDIUM') or define('PTW_RISK_MATRIX_MEDIUM', '#f1e400');
defined('PTW_RISK_MATRIX_HIGH') or define('PTW_RISK_MATRIX_HIGH', '#df1800');

defined('PTW_AO_REASSIGN') or define('PTW_AO_REASSIGN', 1);
defined('PTW_SA_REASSIGN') or define('PTW_SA_REASSIGN', 2);