<?php

defined('SECMAS') or define('SECMAS', 'port_security_master');
defined('SECCERT') or define('SECCERT', 'port_competency_certificate');








defined('WEATHER_CONDITION') or define('WEATHER_CONDITION', 2);
defined('LOCATION') or define('LOCATION', 3);
defined('INCIDENT_POTENTIAL') or define('INCIDENT_POTENTIAL', 4);
defined('AUTHORITIES_INFORM') or define('AUTHORITIES_INFORM', 5);
defined('INCIDENT_CLASSIFICATION') or define('INCIDENT_CLASSIFICATION', 6);
defined('TYPE_OF_NOTIFICATION') or define('TYPE_OF_NOTIFICATION', 7);
defined('CATEGORY_OF_INCIDENT') or define('CATEGORY_OF_INCIDENT', 8);
defined('ROOT_CAUSE_CATEGORY') or define('ROOT_CAUSE_CATEGORY', 9);


defined('INCIDENT_NOTIFICATION_STATUS_GHSE_PENDING') or define('INCIDENT_NOTIFICATION_STATUS_GHSE_PENDING', 1);
defined('INCIDENT_NOTIFICATION_STATUS_GHSE_APPROVED') or define('INCIDENT_NOTIFICATION_STATUS_GHSE_APPROVED', 2);
defined('INCIDENT_NOTIFICATION_STATUS_GHSE_REJECTED') or define('INCIDENT_NOTIFICATION_STATUS_GHSE_REJECTED', 3);

defined('NEAR_MISS') or define('NEAR_MISS', 1);
defined('ACCIDENT') or define('ACCIDENT', 2);

defined('INCIDENT_INVESTIGATION_STATUS_NOT_ASSIGNED') or define('INCIDENT_INVESTIGATION_STATUS_NOT_ASSIGNED', 1);
defined('INCIDENT_INVESTIGATION_STATUS_PENDING') or define('INCIDENT_INVESTIGATION_STATUS_PENDING', 2);
defined('INCIDENT_INVESTIGATION_STATUS_INVESTIGATION_COMPLETED') or define('INCIDENT_INVESTIGATION_STATUS_INVESTIGATION_COMPLETED', 3);
defined('INCIDENT_INVESTIGATION_STATUS_GHSE_APPROVED') or define('INCIDENT_INVESTIGATION_STATUS_GHSE_APPROVED', 4);
defined('INCIDENT_INVESTIGATION_STATUS_GHSE_REJECTED') or define('INCIDENT_INVESTIGATION_STATUS_GHSE_REJECTED', 5);
defined('INCIDENT_INVESTIGATION_NEARMISS_ADDED') or define('INCIDENT_INVESTIGATION_NEARMISS_ADDED', 6);


?>
