<?php


$inspectionTime = [
    '09:00 AM',
    '10:00 AM',
    '11:00 AM',
    '02:30 PM',
    '03:30 PM',

];

defined('INSPECTION_TIME') or define('INSPECTION_TIME', $inspectionTime);

defined('INSPECTION_EXPIRE') or define('INSPECTION_EXPIRE', 3);


defined('MACHINERY_STATUS_GHSE_APPROVE_PENDING') or define('MACHINERY_STATUS_GHSE_APPROVE_PENDING', 1);
defined('MACHINERY_STATUS_GHSE_REJECTED') or define('MACHINERY_STATUS_GHSE_REJECTED', 2);
defined('MACHINERY_STATUS_HSE_INSP_PENDING') or define('MACHINERY_STATUS_HSE_INSP_PENDING', 3);
defined('MACHINERY_STATUS_HSE_INSP_REJECTED') or define('MACHINERY_STATUS_HSE_INSP_REJECTED', 4);
defined('MACHINERY_STATUS_TAG_ISSUED') or define('MACHINERY_STATUS_TAG_ISSUED', 5);
defined('MACHINERY_STATUS_ACTIVE') or define('MACHINERY_STATUS_ACTIVE', 6);
defined('MACHINERY_STATUS_EXPIRED') or define('MACHINERY_STATUS_EXPIRED', 7);
