<?php

defined('HIRADC_DOCUMENT_EAI') or define('HIRADC_DOCUMENT_EAI', 1);
defined('HIRADC_DOCUMENT_HIRADC') or define('HIRADC_DOCUMENT_HIRADC', 2);
defined('HIRADC_DOCUMENT_RISK_REGISTER') or define('HIRADC_DOCUMENT_RISK_REGISTER', 3);

defined('HIRADC_COLORCODE_LOW') or define('HIRADC_COLORCODE_LOW', '#0ca747');
defined('HIRADC_COLORCODE_MEDIUM') or define('HIRADC_COLORCODE_MEDIUM', '#f1e400');
defined('HIRADC_COLORCODE_HIGH') or define('HIRADC_COLORCODE_HIGH', '#df1800');

defined('HIRADC_STATUS_PENDING') or define('HIRADC_STATUS_PENDING', 1);
defined('HIRADC_STATUS_APPROVED') or define('HIRADC_STATUS_APPROVED', 2);
defined('HIRADC_STATUS_REJECTED') or define('HIRADC_STATUS_REJECTED', 3);

defined('HIRADC_ACTIVE_STATUS') or define('HIRADC_ACTIVE_STATUS', 1);
