<?php

defined('WASTE_STATUS_GHSE_PENDING') or define('WASTE_STATUS_GHSE_PENDING', 1);
defined('WASTE_STATUS_GHSE_REJECTED') or define('WASTE_STATUS_GHSE_REJECTED', 2);
defined('WASTE_STATUS_APPROVED') or define('WASTE_STATUS_APPROVED', 3);

defined('WASTE_CATEGORY_WASTE_FORM') or define('WASTE_CATEGORY_WASTE_FORM', 1);
defined('WASTE_CATEGORY_WASTE_LOCATION') or define('WASTE_CATEGORY_WASTE_LOCATION', 2);
defined('WASTE_CATEGORY_FORM_IN_ROOM_TEMP') or define('WASTE_CATEGORY_FORM_IN_ROOM_TEMP', 3);
defined('WASTE_CATEGORY_SOLUBILITY_IN_WATER') or define('WASTE_CATEGORY_SOLUBILITY_IN_WATER', 4);
defined('WASTE_CATEGORY_DENSITY') or define('WASTE_CATEGORY_DENSITY', 5);
defined('WASTE_CATEGORY_RISKS') or define('WASTE_CATEGORY_RISKS', 6);
defined('WASTE_CATEGORY_PPE') or define('WASTE_CATEGORY_PPE', 7);
defined('WASTE_CATEGORY_METHOD_OF_DISPOSAL') or define('WASTE_CATEGORY_METHOD_OF_DISPOSAL', 8);


defined('INVENTORY_ADD') or define('INVENTORY_ADD', 1);
defined('INVENTORY_DISPOSAL') or define('INVENTORY_DISPOSAL', 2);

