<?php

defined('CHEMICAL_CATEGORY_PFOC') or define('CHEMICAL_CATEGORY_PFOC', 1);
defined('CHEMICAL_CATEGORY_TOCMEC') or define('CHEMICAL_CATEGORY_TOCMEC', 2);
defined('CHEMICAL_CATEGORY_TOCMPPE') or define('CHEMICAL_CATEGORY_TOCMPPE', 3);
defined('CHEMICAL_CATEGORY_UOC') or define('CHEMICAL_CATEGORY_UOC', 4);
defined('CHEMICAL_CATEGORY_HC') or define('CHEMICAL_CATEGORY_HC', 5);

defined('CHEMICAL_STATUS_SUPERVIOER_PENDING') or define('CHEMICAL_STATUS_SUPERVIOER_PENDING', 1);
defined('CHEMICAL_STATUS_SUPERVIOER_REJECTED') or define('CHEMICAL_STATUS_SUPERVIOER_REJECTED', 2);
defined('CHEMICAL_STATUS_GHSE_PENDING') or define('CHEMICAL_STATUS_GHSE_PENDING', 3);
defined('CHEMICAL_STATUS_GHSE_REJECTED') or define('CHEMICAL_STATUS_GHSE_REJECTED', 4);
// defined('CHEMICAL_STATUS_APPROVED') or define('CHEMICAL_STATUS_APPROVED', 5);

//NEW 
defined('CHEMICAL_SUPERVIOR_PENDING') or define('CHEMICAL_SUPERVIOR_PENDING',1);
defined('CHEMICAL_SUPERVIOR_REJECTED') or define('CHEMICAL_SUPERVIOR_REJECTED',2);
defined('CHEMICAL_ACKNOWLEDGMENT_PENDING') or define('CHEMICAL_ACKNOWLEDGMENT_PENDING',3);
defined('CHEMICAL_STATUS_APPROVED') or define('CHEMICAL_STATUS_APPROVED',4);



